"""remove message summary and added session summary

Revision ID: 20bba5ffa588
Revises: e12c0ed5056e
Create Date: 2026-01-02 14:55:13.866961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20bba5ffa588'
down_revision: Union[str, Sequence[str], None] = 'e12c0ed5056e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'summary')
    op.add_column('sessions', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'summary')
    op.add_column('messages', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
