"""add session summary

Revision ID: e12c0ed5056e
Revises: a26ed58320d0
Create Date: 2026-01-02 14:39:42.004950

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e12c0ed5056e"
down_revision: Union[str, Sequence[str], None] = "a26ed58320d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("summary", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "summary")
    # ### end Alembic commands ###
